### ISSUE TITLE
LOWESS smoother parameter interface is not intuitive (scatter plot and moran scatter plot)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lixun910/geoda#154]
```
the help window should include specific values for the parameters. the 
bandwidth seems to be a fraction, but a fraction of what? should be based on 
actual distances.
```

Original issue reported on code.google.com by `lanse...@gmail.com` on 25 Jun 2015 at 4:37

**Comment by jkoschinsky** [comment]
when bandwidth is set to 1, it should be identical to linear reg but it's not. Why? (using starting XY at zero Y point for intercept?)

why does delta influence results?

**Comment by lixun910** [comment]
Summary: The LOWESS algorithm in GeDa generates the same results with R's LOWESS; LOESS (which uses different algorithm to determine 'local' than LOWESS) smoother can be identical to a linear regression. 

 LOWESS vs. LOESS vs. Linear in R. 
X: cars$speed 
Y:cars$dist

1) LOWESS vs Linear
plot(cars, xlab = "Speed (mph)", ylab = "Stopping distance (ft)", las=1)
abline(lm(dist ~ speed, data=cars))
lines(lowess(cars$speed, cars$dist, f = 1, iter =1000, delta=diff(range(cars$speed))), col = "red")
lines(lowess(cars$speed, cars$dist, col="blue")
![screen shot 2015-09-21 at 11 14 32 am](https://cloud.githubusercontent.com/assets/2423887/10000609/1691e6b4-6052-11e5-9c53-f3505fd5ea5f.png)

This is the result in R.
The black line is linear regression.
The blue line is LOESS with default parameters.
The red line is LOESS with Bandwidth=1, Iter=1000, Delta Factor=1

It is the same with what GeoDa generated. --- That means the LOWESS algorithm in GeoDa is correct.

![screen shot 2015-09-21 at 11 36 55 am](https://cloud.githubusercontent.com/assets/2423887/10001638/99210cc2-6057-11e5-86cd-2c25d6129762.png)

2) LOESS (which is different than LOWESS) vs Linear
plot(cars, xlab = "Speed (mph)", ylab = "Stopping distance (ft)", las=1)
lines(cars$speed, predict(loess(dist ~ speed, cars, span=100, degree=1)), col="green")
lines(cars$speed, predict(loess(dist ~ speed, cars, span=100, degree=2)), col="red")
abline(lm(dist ~ speed, data=cars))
![screen shot 2015-09-21 at 11 59 25 am](https://cloud.githubusercontent.com/assets/2423887/10001803/6753a0c8-6058-11e5-9f9d-a85aa1af37c1.png)

When "span" is large enough and "degree" of polynomial =1, the smoother is close to a linear regression.

3) The algorithms differ considerably in their details (LOWESS vs LOESS). In determining 'local' LOESS() uses a tricubic weighting, LOWESS() uses a uniform weighting (on reading the code). -- I think that's why LOWESS with parameter bandwidth=1 is not approximate to a linear regression.

Here is a discussion of (Loess vs Lowess) https://stat.ethz.ch/pipermail/bioconductor/2003-September/002337.html

Here is the manual of LOESS: https://stat.ethz.ch/R-manual/R-patched/library/stats/html/loess.html
Here is the manual of LOWESS: https://stat.ethz.ch/R-manual/R-patched/library/stats/html/lowess.html
