### ISSUE TITLE
Averages Chart: save dummy variables to Tables

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lixun910/geoda#166]
```
Averages Chart: save dummy variables to Tables
```

Original issue reported on code.google.com by `lixun...@gmail.com` on 30 Jun 2015 at 3:20

**Comment by jkoschinsky** [comment]
I don't see the "Save Dummy Variable" option in either the Options Menu for the Averages Chart or the right-click option?

**Comment by lixun910** [comment]
Replace save dummy to DID test

**Comment by jkoschinsky** [comment]
"Save Dummy Var to Table" prompts you to export a new data table. Instead, can we just load the save selection dialog (or automatically add a 0-1 variable like in save selection)?

**Comment by lixun910** [comment]
There is a case for "time" or "space and time" comparison, the row of dummy
variables will be more than the opened table, so that's why we need to
export the dummy variable to a new table. So, we can't do that
automatically.

As Luc mentioned, the saved dummy table can be run separately in GeoDa or
in R.

**Comment by jkoschinsky** [comment]
ok, got it.

Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
