### ISSUE TITLE
pseudo p-value poorly positioned in Moran randomization

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#234]
Pseudo p-value is poorly positioned in default randomization window that comes up first - see attached. Of course, it is possible to resize the window, but first impressions matter.
<img width="443" alt="screen shot 2015-10-20 at 10 00 50 am" src="https://cloud.githubusercontent.com/assets/4008351/10609407/99621cc8-7711-11e5-91db-be897931ab5e.png">

**Comment by jkoschinsky** [comment]
It now doesn't overlap with the text anymore, which is great, but still looks really skinny :)

Could you make each line a little thicker for 999 permutations? They're thick for 99, 199, and 499 but then get paper-thin for 999. The thicker lines use up the width of the dialog better.

![screen shot 2015-11-09 at 12 09 11 pm](https://cloud.githubusercontent.com/assets/13679743/11040518/b5e62ec4-86da-11e5-91c4-65f042ce6383.png)

**Comment by lixun910** [comment]
fix in ci 4585028.

This fix only guarantees that at default window size, the 999 permutation
occupies the whole width of the screen. The reason that it is skinny is
because there are more bins for 999 permutation, and the width of the
screen is not big enough for these bins. Of course the width of each
bin can be calculated as (screen_width/#bins), however,  wxWidgets only
accepts integer width when drawing rectangle — which means the width
of bin is rounded as floor(screen_width/#bins). And this round caused
the whole plot not using the full width of screen -- which will cause "skinny" looking. 

You will see the same issue when you use 1999 permutation. However, the user can always
resize the window to get a better rendered plot. -- this fix also includes a bug fixing that resizing not working correctly.

**Comment by jkoschinsky** [comment]
JK: verify in Windows

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.89 (Win 7 Professional (64-bit)).
