### ISSUE TITLE
Update global and local bivariate Moran's I

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#276]
Problem: users are confused by what the bivariate Moran's I is (both global and local):

Solution: Rename the global and local versions "Differential Moran's I" and limit the specification of the following variable as input:
* Variable X at one time period (t0) and same variable X at later time period (t1)
* Based on this input, we automatically compute first differences of this variable on the backend: Xt1 - Xt0
* For the global Moran's I, we then have: X = Xt1 - Xt0 and Y =  spatial lag of this
* Same idea for local Moran's I where X = Xt1 - Xt0 vs. the spatial lag of this X, with local permutations

The idea of this is to test if clusters persist at a later time while controlling for their existence in a previous time.

**Comment by lixun910** [comment]
A solution has been designed and implemented as following:
![screen shot 2016-01-06 at 3 40 15 pm](https://cloud.githubusercontent.com/assets/2423887/12157903/a262fc2a-b492-11e5-8bee-33a560ed164e.png)

However, I found this design brings more questions for users:
to run this differential Moran, users have to use Time-defined dataset, which is not trivial. User might just want to check the differential Moran between, for example, HR60 and HR70. This design won't allow user to do it unless a time variable is setup.

So, I've come with another solution, that we ask the users to select two variables (as the old style Variable selection dialog) for differential Moran's I (which can be notified from the menu item and the title of the dialog). But, the underneath code of "bivariate Moran's I" will be replaced with differential Moran's I.

**Comment by lanselin** [comment]
Actually, the initial idea was to *limit* the use of the bivariate (now differential) Moran to only
those cases where time differences were used. All the other case, such as the HR60 and HR70
example are confusing and counter-intuitive, unless one knows absolutely what one is doing.
Since those cases can always be constructed “by hand” (e.g., by computing the differences in the
calculator), I don’t think they should be facilitated in the interface. The objective is to only use
this statistic in the Time-defined case, so the current interface (below) is good. Maybe it should
be disabled unless one uses a Time-defined case.
I really don’t want the “average” user to compute a bivariate Moran because it is not interpreted
correctly. Basically, we are doing away with it, except in this specific time difference case.
L.

**Comment by lixun910** [comment]
Understand now. Will keep the original design.

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.85 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
