### ISSUE TITLE
Save results

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#278]
Right now, users have to go through two steps to save a variable (see below): Check the variable box and then click on "add variable". Let's streamline this for all save results so it's only one step.

<img width="669" alt="screen shot 2015-11-24 at 8 59 09 pm" src="https://cloud.githubusercontent.com/assets/13679743/11388018/46339952-92ee-11e5-9e35-efe6ed66758c.png">

**Comment by lixun910** [comment]
![screen shot 2015-12-29 at 12 26 39 pm](https://cloud.githubusercontent.com/assets/2423887/12040573/7065b88c-ae27-11e5-88f5-340b205b9455.png)
By default name of each column (e.g. G, C_ID, PP_VAL) will be used to save (with overwrite existing) results.

**Comment by lanselin** [comment]
it shouldn’t overwrite since one may want to have different versions of this.
how about a design where there is a box for the variable name next to the
item with the default value already filled in. one could then change the 
variable name, if necessary and it should just be added to the table.
there should be no need to do “add variable”first.

Luc Anselin, PhD
Regents’ Professor and Walter Isard Chair
Director, GeoDa Center for Geospatial Analysis and Computation
Arizona State University

**Comment by lixun910** [comment]
Sounds good. Will do.

**Comment by jkoschinsky** [comment]
This works. Note: If you save the results initially and then change e.g. the # of permutations or p-value, and then save again, there's no warning about overwriting the initial results but there's the option to change the variable name if the user remembered that they already saved the results before.

Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
