### ISSUE TITLE
toolbar in mac looks been trimmed

### ISSUE THREAD

**Issue by lixun910** [lixun910/geoda#283]
This is related to #262 Reorganize menu and toolbar.

**Comment by lixun910** [comment]
![screen shot 2015-12-02 at 3 21 03 pm](https://cloud.githubusercontent.com/assets/2423887/11546096/5dbb9780-9908-11e5-9fd2-c2c6353193ed.png)

Fixed with advanced toolbar in wxWidgets, which also means be ready for bigger and nicer icons.

**Comment by jkoschinsky** [comment]
great - will still wait with submmitting this to crowdsourced design until
the  order of the icons is fixed. thx!

On 2 December 2015 at 15:22, Xun Li <notifications@github.com> wrote:

> [image: screen shot 2015-12-02 at 3 21 03 pm]
> <https://cloud.githubusercontent.com/assets/2423887/11546096/5dbb9780-9908-11e5-9fd2-c2c6353193ed.png>
>
> Fixed with advanced toolbar in wxWidgets, which also means be ready for
> bigger and nicer icons.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lixun910/geoda/issues/283#issuecomment-161452699>.
>



-- 
************************
Julia Koschinsky, Ph.D.
Research Director
Associate Research Professor
Arizona State University
School of Geographical Sciences and Urban Planning
GeoDa Center for Geospatial Analysis and Computation
julia.koschinsky@asu.edu

http://geodacenter.asu.edu
http://www.facebook.com/geodacenter
http://twitter.com/GeoDaCenter

**Comment by jkoschinsky** [comment]
GeoDa 1.7.75 (OSX Yosemite, 10.10.5)

1. I changed the screen resolution to the smallest available in Yosemite (not sure whether it's 800x600 or sth else since they got rid of the #s).
2. In the toolbar the last icon (Regression) is moved to access through the dropdown
3. However, when I click on the dropdown and then on regression, the program crashes:

<img width="445" alt="screen shot 2016-02-11 at 9 32 38 am" src="https://cloud.githubusercontent.com/assets/13679743/12982655/ef7df10a-d0a2-11e5-9b0f-645303625be7.png">

**Comment by lixun910** [comment]
please verify in 1.7.77

**Comment by jkoschinsky** [comment]
Keeping this open till dropdown on toolbar is gone in next test version.

**Comment by lixun910** [comment]
Please verify in 1.7.87

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.87 (OSX Yosemite, 10.10.5).

Leaving ticket open since default size of Windows toolbar still has dropdown.

**Comment by lixun910** [comment]
Please verify in 1.7.89

**Comment by jkoschinsky** [comment]
Problem persists in GeoDa 1.7.89 for Win 7 Pro:

![toolbar](https://cloud.githubusercontent.com/assets/13679743/13546496/d9a786c6-e26c-11e5-90a2-678199f51fbf.png)

**Comment by lixun910** [comment]
please verify in 1.7.91

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.91 (Win 7 Professional (64-bit)).

Changed screen resolution to 800x600 and it works although each view individually fills up the whole screen, so multi-view analysis is not very feasible. Since 800x600 is rare this is mainly concern with presentations on low-res projectors ...
