### ISSUE TITLE
weights not loaded but shows in "Choose Weights" dialog

### ISSUE THREAD

**Issue by lixun910** [lixun910/geoda#287]

**Comment by jkoschinsky** [comment]
GeoDa 1.7.75 (OSX El Capitan) and Win 7 Professional (64-bit).

When you create a new weights file it is automatically loaded in the weights manager. I'm assuming this is actually the behavior we want. Whatever weights you created last is selected as the default.

Handing back to Xun since I'm not sure what the initial "bug" was.

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.83 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
