### ISSUE TITLE
crash Averages Chart: .gda file

### ISSUE THREAD

**Issue by jkoschinsky** [lixun910/geoda#344]
[nyc_test.zip](https://github.com/lixun910/geoda/files/155688/nyc_test.zip)

Replicable crash:
1. open shapefile
2. open time editor
3. load gda file in time editor
4. open averages chart: specify kids grouped variable
5. program crashes

I suspect this is still related to the path problem from before but the shapefile and .gda file are in the same directory. Even after correcting the weights file path and name to:

                        <path>nyc_sampledata/NYC_Sub_borough_Area_knn4.gwt</path>

the crash persists.

**Comment by lixun910** [comment]
I think you are using older version to get this crash. 
In 1.7.85, in step 3 load gda file in time editor. Since trying to load a wrong .gda file, It will report an error to prevent a crash "GeoDa cannot find one or more associated datasource defined in GeoDa project file. Details: Datasource not exists: ....."

**Comment by jkoschinsky** [comment]
I used 1.7.85 -- I sometimes get it to crash, so there's still sth unstable
in there. Will try to track it.

**Comment by lixun910** [comment]
Please verify in 1.7.87

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.7.87 (OSX Yosemite, 10.10.5).
