### ISSUE TITLE
spatial correlogram dialog issues

### ISSUE THREAD

**Issue by lanselin** [lixun910/geoda#375]
the dialog to specify the settings for the spatial correlogram disappears after a correlogram is drawn. so when one wants to change one of the options, one has to start over. the dialog also does not remember the last variable used, so that one literally has to start over and select the variable again.

also, the Apply button needs to be clicked, Return does not work

finally, why is random sample the default with 1,000,000 iterations even for small data sets. for example, for Nepal there are 75 observations with 2775 pairs, so why have random sample as the default. the results for the full calculation and the random sample seem identical.

**Comment by lanselin** [comment]
better behavior for the dialog would be similar to the lowess parameter setting.

**Comment by lixun910** [comment]
A proposed solution will brings back the original design: the correlogram parameter dialog will shows up (not close) after click "Apply".  This is related to a request in issue #171.

For "random vs Allpairs", a simple logic is added: if number of observations > 5000, then "Random Sample" will be checked. Otherwise "All pairs" will be checked. 

Please verify in 1.8.13

**Comment by jkoschinsky** [comment]
Verified fix in GeoDa 1.8.13 (OSX Yosemite, 10.10.5 and Win 7 Professional (64-bit)).
